<section id="proyectos" class="section projects-section section-dark" aria-labelledby="projects-title">
    <span id="empresa" class="anchor-alias" aria-hidden="true"></span>
    <div class="container">
        <div class="section-heading"><div><p class="eyebrow">02 / DESARROLLOS A MEDIDA</p><h2 id="projects-title">Ideas que ya están<br> <span>trabajando.</span></h2></div><p>Cada negocio tiene su manera de hacer las cosas.<br> Desarrollamos la tecnología para acompañarlo.</p></div>
        <div class="project-filters" role="group" aria-label="Filtrar proyectos" hidden><button type="button" class="is-active" data-filter="all" aria-pressed="true">Todos los proyectos</button><button type="button" data-filter="sistema" aria-pressed="false">Sistemas de gestión</button><button type="button" data-filter="web" aria-pressed="false">Sitios web</button></div>
        <p class="sr-only" id="filter-status" role="status"></p>
        <div class="projects-grid">
            <article class="project-card project-featured" data-category="sistema">
                <div class="project-featured-copy"><div class="case-eyebrow"><span class="case-dot"></span> CASO DESTACADO <span>EVENTOS & GESTIÓN</span></div><h3>Córdoba Teje</h3><p class="case-headline">Todo un evento.<br> Un solo sistema.</p><p>Una plataforma desarrollada a medida para gestionar el 100% de su operación: desde el primer expositor hasta la validación de la última entrada.</p><div class="tag-list"><span>Expositores y stands</span><span>Cobranzas</span><span>Facturación</span><span>Entradas</span><span>Validación QR</span></div><details class="case-details"><summary>Explorá el proyecto <?= gohIcon('plus') ?></summary><div><p>La administración y el ingreso al evento comparten una misma herramienta.</p><ul><li>Gestión de expositores, clientes y asignación de stands.</li><li>Seguimiento de cobranzas, saldos y facturación.</li><li>Generación de entradas y lector QR para validar el acceso.</li><li>Panel general y reportes para seguir la operación.</li></ul><a class="text-link" href="<?= gohWhatsapp('Hola, vi el sistema de Córdoba Teje y me gustaría conversar sobre un desarrollo para mi negocio.') ?>" target="_blank" rel="noopener noreferrer">Quiero un sistema a medida <?= gohIcon('arrow') ?></a></div></details></div>
                <div class="cordoba-visual"><span class="visual-label"><span class="status-dot"></span> DESARROLLO GOH / CÓRDOBA TEJE</span><div class="case-browser"><div class="cordoba-screen"><img src="img/landing/cordoba-teje.png" width="1718" height="1392" alt="Sistema de Córdoba Teje: panel de expositores, stands, cobranzas, facturación, entradas y lector QR" loading="lazy" decoding="async"></div></div><div class="case-caption"><span>De la organización al acceso.</span><?= gohIcon('arrow') ?></div></div>
            </article>
            <article class="project-card academy-card" data-category="sistema">
                <div class="project-image academy-visual"><img src="img/mockup/globalenglish.png" width="1920" height="1296" alt="Sistema administrativo de Global English Academy en una computadora portátil" loading="lazy" decoding="async"></div>
                <div class="project-body"><span class="project-type">EDUCACIÓN / SISTEMA DE GESTIÓN</span><h3>Global English Academy</h3><p>La administración de la academia, conectada: alumnos, familias, cuotas y pagos. Integración con Mercado Pago y facturación automática con ARCA.</p><details class="case-details"><summary>Conocé la solución <?= gohIcon('plus') ?></summary><div><p>Un desarrollo que reúne la gestión académica y administrativa, permite seguir pagos y reduce la carga manual de la facturación.</p><a class="text-link" href="<?= gohWhatsapp('Hola, me interesa un sistema administrativo para mi academia, como el de Global English.') ?>" target="_blank" rel="noopener noreferrer">Consultar por mi academia <?= gohIcon('arrow') ?></a></div></details></div>
            </article>
            <article class="project-card" data-category="web"><div class="project-image paideia-visual"><img src="img/mockup/paideia_optimized_1766148892.webp" width="1920" height="1080" alt="Sitio web de Paideia Editorial" loading="lazy" decoding="async"></div><div class="project-body"><span class="project-type">EDITORIAL / SITIO WEB</span><h3>Paideia Editorial</h3><p>Una presencia digital para acercar la editorial y sus servicios a nuevos autores y lectores.</p><a class="text-link" href="https://paideiaeditorial.net/" target="_blank" rel="noopener noreferrer">Visitar sitio <?= gohIcon('arrow') ?></a><p class="project-credit">Efectos gráficos junto a <a href="https://www.linkedin.com/in/diego-sebastian-markiewicz/" target="_blank" rel="noopener noreferrer">Diego S. Markiewicz</a>.</p></div></article>
            <article class="project-card" data-category="web"><div class="project-image levalle-visual"><img src="img/mockup/muni_levalle_optimized_1766148863.webp" width="1920" height="1080" alt="Sitio institucional de la Municipalidad de General Levalle" loading="lazy" decoding="async"></div><div class="project-body"><span class="project-type">SECTOR PÚBLICO / SITIO INSTITUCIONAL</span><h3>Municipalidad de General Levalle</h3><p>Información, servicios y pago digital, con una navegación pensada para los vecinos.</p><a class="text-link" href="https://www.generallevalle.gob.ar/" target="_blank" rel="noopener noreferrer">Visitar sitio <?= gohIcon('arrow') ?></a><p class="project-credit">Desarrollado junto a <a href="https://www.linkedin.com/in/diego-sebastian-markiewicz/" target="_blank" rel="noopener noreferrer">Diego S. Markiewicz</a>.</p></div></article>
            <article class="project-card" data-category="web"><div class="project-image herrajes-visual"><img src="img/mockup/oddoherrajes_optimized_1766148886.webp" width="1920" height="1080" alt="Sitio de Oddovero Herrajes con sus productos y acceso a la tienda" loading="lazy" decoding="async"></div><div class="project-body"><span class="project-type">COMERCIO / SITIO WEB</span><h3>Oddovero Herrajes</h3><p>Productos, historia y contacto en una web que conecta a los visitantes con la tienda del negocio.</p><a class="text-link" href="https://goh.com.ar/oddovero_herrajes/a" target="_blank" rel="noopener noreferrer">Visitar sitio <?= gohIcon('arrow') ?></a></div></article>
        </div>
    </div>
</section>
