<section id="estudio" class="section studio-section" aria-labelledby="studio-title">
    <span id="soluciones" class="anchor-alias" aria-hidden="true"></span>
    <div class="container">
        <div class="studio-intro"><div><p class="eyebrow">03 / DETRÁS DEL SOFTWARE</p><h2 id="studio-title">Entendemos tu negocio.<br> <span>Después, escribimos código.</span></h2></div><div class="studio-description"><p>GOH es un estudio de desarrollo liderado por <strong>Gaspar Oddovero Herrera</strong>, desde General Levalle, Córdoba. Creamos productos propios y soluciones a medida para negocios con desafíos reales.</p><p>Hablás con quien construye tu sistema. Desde la primera idea hasta la implementación y las mejoras que vienen después.</p><a class="text-link" href="nosotros.php">Conocé a Gaspar <?= gohIcon('arrow') ?></a></div></div>
        <div class="services-grid"><article><div class="service-icon"><?= gohIcon('code') ?><span>01</span></div><h3>Software a tu medida</h3><p>Convertimos tus procesos en un sistema que ordena el trabajo y conecta las áreas de tu negocio.</p></article><article><div class="service-icon"><?= gohIcon('globe') ?><span>02</span></div><h3>Webs con un objetivo</h3><p>Landing pages, sitios institucionales y tiendas online para presentar tu marca y generar nuevas oportunidades.</p></article><article><div class="service-icon"><?= gohIcon('chat') ?><span>03</span></div><h3>Acompañamiento directo</h3><p>Definimos el alcance, ponemos todo en marcha y seguimos cerca para que puedas aprovechar tu herramienta.</p></article></div>
        <div class="process-strip"><p>DE LA IDEA A TU DÍA A DÍA</p><ol><li><span>01</span> Te escuchamos</li><li><span>02</span> Diseñamos la solución</li><li><span>03</span> La construimos</li><li><span>04</span> Te acompañamos</li></ol></div>
    </div>
</section>
<section class="section faq-section" aria-labelledby="faq-title"><div class="container faq-grid"><div><p class="eyebrow">ANTES DE DAR EL PASO</p><h2 id="faq-title">Hablemos<br> claro.</h2><p>Lo que quizás te estás preguntando.</p></div><div class="faq-list"><details><summary>¿Necesito un producto GOH o un sistema a medida? <?= gohIcon('plus') ?></summary><p>Si administrás un gimnasio o un comercio, GOH GYM y GOH SHOP son el primer lugar para empezar. Si tu operación tiene procesos particulares, podemos evaluar un desarrollo a medida. Lo definimos juntos en la primera charla.</p></details><details><summary>¿Puedo conocer el sistema antes de contratar? <?= gohIcon('plus') ?></summary><p>Sí. Podés solicitar una demo de GOH GYM o GOH SHOP. Conversamos sobre tu negocio y te mostramos cómo la herramienta puede acompañar tu trabajo.</p></details><details><summary>¿Cómo empezamos un desarrollo a medida? <?= gohIcon('plus') ?></summary><p>Nos contás qué necesitás resolver. Relevamos tus procesos y acordamos las funcionalidades, etapas, plazos y presupuesto antes de comenzar.</p></details><details><summary>¿Me acompañan con la implementación? <?= gohIcon('plus') ?></summary><p>Sí. Coordinamos la puesta en marcha y el uso inicial del sistema. El alcance del soporte y las mejoras se define según el producto o la propuesta acordada.</p></details></div></div></section>
